# Generated by Django 5.0.2 on 2026-03-05 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionitem',
            old_name='acquired_date',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='market_price',
        ),
    ]
