# Generated by Django 6.0.3 on 2026-03-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_acquired_date_collectionitem_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
